### ISSUE TITLE
Clutter in the networks view

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1003]
The web UI shows more networks/interfaces than the cli. 

None of the additionally shown interfaces can be used (At least not in my scenario). 

- Loopback interface
- tap interfaces for VMs
- ovs-system

Why are they shown? If not required, can they be filtered out just like the `lxc network ls` output?

```
lxc network ls
+------+----------+---------+------+------+-------------+---------+-------+
| NAME |   TYPE   | MANAGED | IPV4 | IPV6 | DESCRIPTION | USED BY | STATE |
+------+----------+---------+------+------+-------------+---------+-------+
| eno2 | physical | NO      |      |      |             | 0       |       |
+------+----------+---------+------+------+-------------+---------+-------+
| ovs0 | bridge   | NO      |      |      |             | 23      |       |
+------+----------+---------+------+------+-------------+---------+-------+
| wlo1 | physical | NO      |      |      |             | 0       |       |
+------+----------+---------+------+------+-------------+---------+-------+
```

![image](https://github.com/user-attachments/assets/6f2e6884-b733-43be-8a64-4fbf93287c3b)

**Comment by edlerd** [comment]
Thanks for the report, from your description it seems the CLI is filtering out network devices of type `loopback` and `unknown`. We'll check the CLI code and if that turns out to be the logic, it will be very easy for the LXD-UI to adopt the same filter.

**Comment by edlerd** [comment]
Indeed, [LXD is filtering out the type loopback and unknown](https://github.com/canonical/lxd/blob/main/lxc/network.go#L1054), so in the UI we will start to do the same.
