### ISSUE TITLE
Cannot suffix memory limits in project  configuration

### ISSUE THREAD

**Issue by tam1192** [canonical/lxd-ui#1005]
# How to reproduce
1. login
2. Create Project
3. Configuration
4. Resource limits
5. Edit configuration
6. Change “Max sum of memory limits" ( for example, Type “4GiB” to get “4")

## What we tried
- Copy and paste from Notepad : no good
- Direct command line editing : good

## environment
- Windows 11 Pro 24H2 26100.2314
- MS edge 131.0.2903.63 (official build) (64 bit)
- lxd
```
example@user :~$ lxc version
Client version: 5.21.2 LTS
Server version: 5.21.2 LTS
```

# What we want
Support for suffixes
(for example, Type "4GiB" to get "4GiB")

**Comment by edlerd** [comment]
Hello and thank you for the request. This was indeed an oversight as the projects memory limit input should be a size with unit and not just a plain number. I opened a PR with a fix just above.
