### ISSUE TITLE
Creating image from instance doesn't configure alias

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd-ui#1010]
Hey,

running 6.1 candidate
```
Name    Version      Rev    Tracking          Publisher   Notes
core20  20240911     2434   latest/stable     canonical✓  base
core22  20241001     1663   latest/stable     canonical✓  base
core24  20240920     609    latest/stable     canonical✓  base
lxd     6.1-87af004  31392  latest/candidate  canonical✓  -
snapd   2.63         21759  latest/stable     canonical✓  snapd
```

Creating an image from an instance, the alias field doesn't work. I have tried with the default suggested alias and a custom alias `monkey`.

![image](https://github.com/user-attachments/assets/36654c72-c957-47bf-b91a-be0acb74efcd)

The `make publicly available` checkmark does work.

![image](https://github.com/user-attachments/assets/d0b50645-41e7-4d2a-99ae-789713b9a324)

no aliases exist:
```
lxc image alias list
+-------+-------------+------+-------------+
| ALIAS | FINGERPRINT | TYPE | DESCRIPTION |
+-------+-------------+------+-------------+
```

**Comment by vosdev** [comment]
After I set an alias via cli
```
lxc image alias create banana a48bd96185ee
lxc image alias list
+--------+--------------+-----------------+-------------+
| ALIAS  | FINGERPRINT  |      TYPE       | DESCRIPTION |
+--------+--------------+-----------------+-------------+
| banana | a48bd96185ee | VIRTUAL-MACHINE |             |
+--------+--------------+-----------------+-------------+
```

![image](https://github.com/user-attachments/assets/37f9d38e-0c41-4cd5-b706-f4984bd0d2ad)

it is shown in the ui :)

**Comment by edlerd** [comment]
Hello and thank you for the request. I have an idea what might be going wrong. The technical limitations of the API forced the UI to send the request to create the alias only after the image was created. If you reload the browser before the image is finished creating, this second request is never going to be sent.

Did you maybe refresh the page after submitting the image creation modal? That would explain why the alias was not created.

I understand this is not ideal, and we have plans to remove this workaround. Basically, extending the create image endpoint to allow for also submitting an alias that is to be created with the new image. Until that is realized, please don't refresh manually while the image is creating, and the aliasing should work right away.

**Comment by vosdev** [comment]
Ah, it seems I have. I just clicked Create Image and did not touch the browser window until it was done.

That new image now has an alias.

These are also separate api calls via the cli so I understand that this can be difficult to fix.

**Comment by blackwhitebear8** [comment]
This issue seem to still exist in Version 6.3-ui-0.16

**Comment by edlerd** [comment]
> This issue seem to still exist in Version 6.3-ui-0.16

What exactly is the issue you are facing? Did you also refresh or quit the UI tab in the browser while the image was creating?
