### ISSUE TITLE
adding certificate to LXD trust store not working

### ISSUE THREAD

**Issue by aryanrajseo** [canonical/lxd-ui#1022]
Hi, i am new with LXD, trying setting up the UI, SSL certificate is generated however not  able to add it to server.

file downloaded as lxd-ui-192.168.1.1.crt (replaced with actual ip) and also tried duplicating with lxd-ui.crt

```

root@ns8744:~# lxc config trust add Downloads/lxd-ui-192.168.1.1.crt
Error: open /var/lib/snapd/hostfs/root/Downloads/lxd-ui-192.168.1.1.crt: no such file or directory

root@ns8744:~# lxc config trust add Downloads/lxd-ui.crt
Error: open /var/lib/snapd/hostfs/root/Downloads/lxd-ui.crt: no such file or directory

```
```
root@ns8744:~# snap version
snap    2.66.1+24.04
snapd   2.66.1+24.04
series  16
ubuntu  24.04
kernel  6.8.0-49-generic
```

**Comment by edlerd** [comment]
Thank you for the report. Did you upload the certificate to the server where you are trying to add it? From the output above it seems that the file is not found. Did you download it onto your device, but not onto the server?

I'm closing this as it is not an issue with lxd ui itself. It can be seen as a UX issue, and we are already planning to improve the UX for permissions in the first quarter of 2025. Until then, please consult the [LXD forums](https://discourse.ubuntu.com/c/lxd/126) for further questions on usage.
