### ISSUE TITLE
Snapshot page shows “Invalid Date” instead of “No expiry date”

### ISSUE THREAD

**Issue by gagath** [canonical/lxd-ui#1030]
On the snapshots page, when a snapshot is created without an expiry date, the corresponding column displays “Invalid date”. A more sensible display value could be “No expiry date”.

![image](https://github.com/user-attachments/assets/13ae0be2-7a5a-4b16-b777-a51fb066278c)

Version 6.2-ui-0.14

**Comment by edlerd** [comment]
Thank you for the report! We discovered this very recently internally. It was fixed about 3 weeks ago in [this commit](https://github.com/canonical/lxd-ui/commit/e8295c558c278ffb9811695f05799fa630e1b8dd). The fix will be available in the next release.
