### ISSUE TITLE
Snapshot functionality seems incomplete, not working yet? 

### ISSUE THREAD

**Issue by desrod** [canonical/lxd-ui#130]
Fantastic work so far on this UI... absolutely gorgeous and well thought out. As I was poking through all the features and options in my LXD cluster, I realized that snapshots isn't working (yet?), but snapshots do work from the CLI as expected, and those snapshots _do_ show up in the UI in real-time, but I can't _create_ snapshots from the UI, only Restore/Delete existing snapshots. 

I'll keep muddling around with it and see if I've missed something, but that stood out in the first hour of test-driving it.

**Comment by edlerd** [comment]
Thank you for the kind feedback. There is indeed a bug with how the submit button of the snapshot creation is hooked up with submit. I'll merge a fix shortly.
