### ISSUE TITLE
Add network topology

### ISSUE THREAD

**Issue by Sensei-CHO** [canonical/lxd-ui#151]
Hi ! as a heavy user of LXD what I found most complicated is to do was to represent my OVN topology acorss projects and networks.

It could be great to have a openstack horizon like topology to visualize and configure networks across one or more clusters.

![image](https://user-images.githubusercontent.com/73945512/212652485-73153785-983f-4116-b208-bd47e776a5ea.png)

I'm not and expert and I don't know if this could be really helpful for everyone but i'll help if the idea is kept.

Let me know if the idea is good or not and if I have to bring more informations.

**Comment by edlerd** [comment]
Hello @Sensei-CHO,
thank you for the suggestion. A network map or graph is a very good idea. We are just starting with features like container, profile and project management. I think including a network map might be a bit too early, but we can already shape the idea. Once we understand how and what to build, it can be added quite quickly.

How would you imagine a network map? What would be the nodes in the map, instances, projects, or other entities?

**Comment by Sensei-CHO** [comment]
Hi @edlerd ! Thanks for your reply.
It would be great to have a map by project where you have all your instances, their status defined by a color, their connections to networks and some more information when you click on them(like IP addresses for instances or subnet for network).
![image](https://user-images.githubusercontent.com/73945512/213012030-81ff5a5c-199e-455c-b7d6-c87d939cd8f9.png)

It may be too much but having a main network map with all the nodes, clustrer-groups, etc... could be very helpful to have a complete view of your infrastructure.

![image](https://user-images.githubusercontent.com/73945512/213014848-c03daa7e-c5c3-47a2-99ba-a373ed896d4d.png)

I would be happy to help since I've done this before but my knowledge is limited to python.

**Comment by Sensei-CHO** [comment]
Thank you for the advices with the libs. I'll explore them !
