### ISSUE TITLE
dotrun fails with "haproxy not found"

### ISSUE THREAD

**Issue by EpicLPer** [canonical/lxd-ui#194]
I'm playing around with LDX/LXC right now and getting used to it. I've tried installing the UI and ran into a problem.

After running `dotrun` I'm presented with the following error:
```
webpack 5.75.0 compiled successfully in 13487 ms
$ sass static/sass/styles.scss build/ui/styles.css --load-path=node_modules --style=compressed && postcss --use autoprefixer --replace 'build/**/*.css' --no-map
$ watch -p 'static/sass/**/*.scss' -p 'static/js/**/*' -c 'yarn run build'
$ ./entrypoint
booting on https://localhost:9443
./entrypoint: line 27: haproxy: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've already installed `haproxy` via `sudo apt install haproxy` since there was no snap version, but it still says the above error.

I'm currently using Ubuntu 22.04.1 LTS in a VM with the latest upgrades installed to test all of this out.

**Comment by edlerd** [comment]
You are probably running an outdated dotrun version, where the updater is also broken. On boot, dotrun prints `Checking for dotrun image updates...`, but it does not update. Please try to `docker pull canonicalwebteam/dotrun-image`. Afterwards, dotrun should start in a container with haproxy installed.

**Comment by EpicLPer** [comment]
Ah, that might be the problem then. I simply used the snap version of dotrun, should've definitely followed the guide 1 to 1 then :) I'll try!

**Comment by edlerd** [comment]
Right, lxd-ui will only work with the pip version of dotrun.

**Comment by EpicLPer** [comment]
Worked now, thanks! Had another issue with snap now where it couldn't find the keys via the virtual file system it makes, but that's out of the scope for this issue.
