### ISSUE TITLE
Hardcoded port 9443 is occupied by the snap microcloud

### ISSUE THREAD

**Issue by grebennikov** [canonical/lxd-ui#212]
Trying to deploy the UI on the machine where the microcloud snap is installed.
When running "dotrun" - the build process fails with
`docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/cab6cc4470e2ae694c4c4cbc41b80eab42f1662d19e8fa4fee3e934fd69b7829/start: Internal Server Error ("driver failed programming external connectivity on endpoint dotrun-lxd-ui-1677710801 (092d2c89c715d8cec781c06f6c15db977903ad7c32463d2fa8257847eb689063): Error starting userland proxy: listen tcp4 0.0.0.0:9443: bind: address already in use")`

Quick scanning shows that the port 9443 is occupied by the microcloud snap:
`$ sudo netstat -antpl|grep 9443
tcp        0      0 10.113.213.121:9443     0.0.0.0:*               LISTEN      2558/microcloudd`

The port should be configurable and the default value should be changed.

**Comment by edlerd** [comment]
Thank you for reporting this. We will move it to port 8407 shortly.
