### ISSUE TITLE
Is it possible to configure authentication for frontend

### ISSUE THREAD

**Issue by emwadde** [canonical/lxd-ui#220]
The application works very well except for the issue that there is no option to configure authentication for the frontend. It this feature supported or is it on the roadmap?

**Comment by edlerd** [comment]
The dev mode can be with authentication. Just the word `optional` in the [HAProxy config](https://github.com/canonical/lxd-ui/blob/main/haproxy-dev.cfg#L12) needs to be changed to `required` to get certificate based auth. Then you need to have the cert imported to your browser to access the UI.

The version of the UI shipped with LXD edge makes this type of auth mandatory as well.

We do plan to work on auth in the future. To my knowledge LXD itself is planning some changes there, hence we postpone it until their plan is stable.
