### ISSUE TITLE
Communication Error

### ISSUE THREAD

**Issue by irtaza9** [canonical/lxd-ui#296]
I've depoly my lxd server and everything work fine on linux commad line. But I want to manage all the operation over http restful apis which is available in official documentation. I've certificate and key. Now how can I call https://Ixd-host.secret.com/1.0/containers:8443 from any postman or javascript or php or anyother language?

**Comment by irtaza9** [comment]
Got it, I've opened an [issue](https://github.com/lxc/pylxd/issues/537), can you please look into it and guide me accordingly.

**Comment by edlerd** [comment]
The issues section here is for feature requests and bug reports. If you have usage questions, please stick to the [public forum](https://discuss.linuxcontainers.org/) for LXD.

**Comment by irtaza9** [comment]
Sure, I apologize for the confusion in my previous response. The best place to ask usage questions about LXD and Pylxd would be on the LXD forum or the Pylxd GitHub repository's issue tracker. They have communities that can provide support and guidance on using these tools.
