### ISSUE TITLE
Page Not Found 404 Page/Error Not Shown Consistently.

### ISSUE THREAD

**Issue by evoelise** [canonical/lxd-ui#326]
If I select a non-existent page such as `https://myserver:8443/ui/default/instancesx` then a nice "404 Page not found" error is shown.

But on other pages such as `https://myserver:8443/ui` then JSON is shown on the screen - 

`{"type":"error","status":"","status_code":0,"operation":"","error_code":404,"error":"not found","metadata":null}`

Possibly as this path exists but no page is specified?

This is inconsistent and the JSON does not mean much to the user and there's no way back to a valid web page from here.

**Comment by edlerd** [comment]
> But on other pages such as `https://myserver:8443/ui` then JSON is shown on the screen -

I think this is beacuse the `/ui` url is not known, only the `/ui/` directory. Which arguably might be confusing. We'll check with LXD core, if the `/ui` path can redirect or handled in the same way as the `/ui/`.

**Comment by stgraber** [comment]
Can be closed now that we've merged https://github.com/lxc/lxd/pull/11654
