### ISSUE TITLE
Allow Easy Creation of VM from an ISO

### ISSUE THREAD

**Issue by evoelise** [canonical/lxd-ui#328]
Currently "Create an instance" only allows base images that are in the LXD image repo.

I am sure you have plans for users to be able to add their own images repos and to select from them etc. But for news users and those just starting to play with LXD it would be good to be able to create a VM straight from an iso. So have something like a radio select on the "Create an instance" that allows "Base Image" or from "Install from .iso". This probably auto-mounts the ISO and adds to the VM before starting it. Installing from an .iso has some advantages especially where custom installs are wanted (and use hasn't wrapped their head around `cloud.init` yet if this is even supported by the O/S).

Kind of related to this, from a user point of view from using this UI it makes sense to me to have a selection of Container/VM as the first thing on the "Create an instance" page rather than selecting this later when the image is selected (I found this initially confusing). Selecting Container/VM first then just shows compatible images if installing from an image.

**Comment by edlerd** [comment]
The iso support pr was merged and I'll close this for now. If you are missing a feature please let us know.
