### ISSUE TITLE
Breadcrumb is Missing for Storages Page

### ISSUE THREAD

**Issue by evoelise** [canonical/lxd-ui#332]
On other pages such as instances and profiles as you drill down into pages a breadcrumb is shown top-left (e.g. Profiles > default) that allows you click the previous page name to traverse back up the chain.

This is missing from the Storages page. 

If you click on default in storages - it should show "Storages > default" top left with the "Storages" part being a link to take you back to the default Storages page.

**Comment by edlerd** [comment]
Thank you for the report. Your suggesting is a fairly small change, so I could realize them in the PR above.

To give more background:
Parts of the UI are considered more final (instances, profiles and projects). And the other parts (storage, network, configuration, cluster, settings, warnings) result from prototyping without proper design and thinking the use-cases through. We plan to work on storage (and cluster, as well as networks) in the coming 6 months to lift the feature to a more stable place.
