### ISSUE TITLE
UI Should Prohibit Certain Symbols from Snapshot Names

### ISSUE THREAD

**Issue by evoelise** [canonical/lxd-ui#334]
The UI should only allow valid characters for names when creating or editing Snapshots.

Creating:
![lxd ui screenshot 3](https://github.com/canonical/lxd-ui/assets/1719167/d957c2e2-03d6-42a0-bf83-aa2f98582965)
Editing:
![lxd ui screenshot 4](https://github.com/canonical/lxd-ui/assets/1719167/aece9088-7fa6-48c5-b9fd-40322ed1f483)

**Comment by edlerd** [comment]
Thank you for reporting this @evoelise 
We just merged a fix for allowing only some characters in snapshots. You can expect LXD 5.20 to include the fix.
