### ISSUE TITLE
Require selecting a storage pool, or leave the selected one

### ISSUE THREAD

**Issue by ru-fu** [canonical/lxd-ui#342]
I used the UI to create an instance and wanted to increase the storage pool size, so I configured that before launching the instance:
![Screenshot from 2023-05-12 14-00-13](https://github.com/canonical/lxd-ui/assets/11227796/5896a636-09e5-460d-9ff9-073e38416a91)

The result was:
`Failed creating instance record: Failed initialising instance: Invalid devices: Device validation failed for \"root\": Root disk entry must have a \"pool\" property set`

Before I selected "Root storage pool" to configure the size, the `default` pool was selected there, so I didn't even look at the dropdown (the only thing I wanted to change was the size).
But as soon as I selected "Root storage pool", the dropdown selection changed to "Select option", and it let me launch the instance without selecting anything, which caused the error.

It makes sense in hindsight, but I think we could improve the usability here - either by requiring a pool to be selected, or by keeping the dropdown on `default` unless something else is selected.

**Comment by edlerd** [comment]
Thank you for the report, I think selecting the 1st pool automatically is in the user intend, and the above PR is performing that change.
