### ISSUE TITLE
Is lxd-ui intended to replace the SNAP 'workshops' for LXD containers app

### ISSUE THREAD

**Issue by bmullan** [canonical/lxd-ui#411]
**[SNAP workshops for LXD](https://snapcraft.io/install/workshops/ubuntu)** has been around for awhile

_Is the **_lxd-ui_** intended to essentially replace the LXD container only "workshops"_

Thanks
brian

**Comment by edlerd** [comment]
I think workshops will coexist for at least two reasons:
1. As an Ubuntu desktop app, focusing on a different use case.
2. Easier to get started with.

There is progress on workshops with recent commits and releases. LXD-UI on the other hand is giving more detail and exposing a wider part of LXD configuration, focusing on slightly advanced use-cases.
