### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by ThinkFar** [canonical/lxd-ui#416]
Hello, total noob here!

I am looking to make the lxd-ui available on my domain (lxd.domain.com) using NGINX reverse proxy mananger. 
I already have a bunch of my servers applications running through this reverse proxy, but I cannot get it to work for LXD-UI. I am guessing it has something to do with the certificates, but not too sure. I know too little about that stuff unfortunately.

I appreciate any help and love the project!
Keep it up!

**Comment by edlerd** [comment]
You can put a proxy in front of LXD, but you have to run it in TCP mode (layer 4). So the client certificate you have in your browser gets forwarded to LXD and it can verify it is you.

If the proxy is running in http mode (layer 7) it will terminate the connection and not be able to forward your cert. You could make the cert available to the proxy itself, but then everyone using the proxy would be automatically authenticated, which seems like a security risk.
