### ISSUE TITLE
How to install on production LXD?

### ISSUE THREAD

**Issue by Igorgro** [canonical/lxd-ui#417]
I have an LXD installed from arch linux package (https://archlinux.org/packages/extra/x86_64/lxd/), not snap. How I can install LXD-UI to it? I tried to build lxd-ui using `yarn build` and move `build/` directory to /var/lib/lxd, but this didn't help, there still no ui available (even after restarting LXD). Where should I place compiled files to make LXD serving them? `ARCHITECTURE.md` does not contain this information

**Comment by Igorgro** [comment]
Ok, I found how to do that. The full instruction
1. Clone this repo
2. `yarn && yarn build`
3. Copy `build/ui` directory to `/var/lib/lxd`
4. Change the `LXD_UI` environment variable of LXD. This can be done using `systemctl edit lxd` command. In that file add the following lines:
    ```ini
    [Service]
    Environment=LXD_UI=/var/lib/lxd/ui
    ```
5. `systemctl deamon-reload && systemctl restart lxd`
6. Set `core.https_address` of LXD to make it listen for remote connections
7. Open `<your-server-ip>:8443` and see UI

**Comment by edlerd** [comment]
Closing this, as it is not an issue we can fix in the UI.

**Comment by Igorgro** [comment]
Can this be pinned or placed somewhere in docs?

**Comment by edlerd** [comment]
I added a wiki page with your setup here: https://github.com/canonical/lxd-ui/wiki/Build-the-UI-for-Arch-and-other-Linux-Distributions

**Comment by lateautumn233** [comment]
> Ok, I found how to do that. The full instruction
> 
> 1. Clone this repo
> 2. `yarn && yarn build`
> 3. Copy `build/ui` directory to `/var/lib/lxd`
> 4. Change the `LXD_UI` environment variable of LXD. This can be done using `systemctl edit lxd` command. In that file add the following lines:
>    ```ini
>    [Service]
>    Environment=LXD_UI=/var/lib/lxd/ui
>    ```
> 5. `systemctl deamon-reload && systemctl restart lxd`
> 6. Set `core.https_address` of LXD to make it listen for remote connections
> 7. Open `<your-server-ip>:8443` and see UI

systemctl daemon-reload && systemctl restart lxd
daemon not deamon
