### ISSUE TITLE
Add support for assigning NVIDIA MIG GPU instances to containers

### ISSUE THREAD

**Issue by danboid** [canonical/lxd-ui#420]
We are in the process of setting up a HPC GPU server and it would be good if we could create new containers and assign NVIDIA MIG GPU UUID's to containers without having to use the lxc command line tool.

Is this a planned feature?

Thanks

**Comment by edlerd** [comment]
Thank you for the request, adding special device support was not yet on our roadmap. It sounds quite straightforward, we'll consider adding it.

You can already configure Nvidia GPUs in the LXD UI with the custom YAML input. It is available when creating or editing a container. I guess those are added as a custom device for which you'd need to add some lines to the configuration.

**Comment by danboid** [comment]
Thanks @edlerd !

**Comment by edlerd** [comment]
GPU support landed recently and is available now on the latest/edge channel of the LXD-UI. Though we opted to not support the MIG configuration in the UI as it is a rather special use case. But again, the YAML editor in the UI should allow for setting it also from the UI. It will be part of one of the next releases.
