### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by ZubikIT** [canonical/lxd-ui#423]
After install maas not up lxdbr0

`июл 28 07:52:04 supermicro systemd-networkd[1005]: lxdbr0: Link DOWN
июл 28 07:52:05 supermicro lxd.daemon[1592]: time="2023-07-28T04:52:05Z" level=error msg="Failed initializing network" err="Failed starting: The DNS and DHCP service exited prematurely: Process exited with non-zero value 2 (\"dnsmasq: failed to create listening socket for 10.10.10.1: Address already in use\")" network=lxdbr0 project=default
июл 28 07:53:05 supermicro systemd-networkd[1005]: lxdbr0: Link UP
июл 28 07:53:05 supermicro audit[5747]: AVC apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="lxd_dnsmasq-lxdbr0_</var/snap/lxd/common/lxd>" pid=5747 comm="apparmor_parser"
`

**Comment by edlerd** [comment]
This sounds like a problem with MAAS. This is the repository for the user interface of LXD. You might get support from the Maas community at https://discourse.maas.io/
