### ISSUE TITLE
No metrics displayed if user is restricted to see just one project

### ISSUE THREAD

**Issue by matjazp** [canonical/lxd-ui#426]
If I set with lxc config trust that user is restricted to a certain restricted project (project was auto-created by using multi-user setup), ui doesn't show Usage and is just displaying indefinitely "Loading metrics ...".

If I again set user to see all projects (with lxc config trust edit xxxxyyyyzzzz, set restricted to false), GUI shows everything, including metrics for an instance in user-1000 project.

**Comment by matjazp** [comment]
Extra info from console:

InstanceDetail-63fcc5d9.js:4     GET https://88.200.23.238:8443/1.0/metrics 403

So something about authorisation when user can only see a single restricted project?

**Comment by matjazp** [comment]
Extra info from console:

InstanceDetail-63fcc5d9.js:4 GET https://IP:8443/1.0/metrics 403

So something about authorisation when user can only see a single restricted project?

**Comment by edlerd** [comment]
Hello, thank you for the report.

The UI does not handle users with reduced permissions yet. Those can't read the metrics API as you pointed out correctly. There might be other actions or data that is not allowed to access. We'll look into fixing this shortly.

A plan would be to
1. Figure out how to identify the permissions for the active user
2. Find all components that need to adjust to reduced permissions
3. Create a central place to define permissions 
4. Adjust the components from 2.

**Comment by matjazp** [comment]
Plan sounds great. Restrictions on a project level are among best features of LXD.
