### ISSUE TITLE
When selecting base image, Ubuntu images should show 22.04 version number, not just jammy

### ISSUE THREAD

**Issue by lathiat** [canonical/lxd-ui#429]
When creating a VM and you click "Select base image", the offered Ubuntu releases simply have the shortname (e.g. focal, jammy, lunar). Ideally it would also display the release version (e.g. 22.04, for jammy). It would be even better if it indicated which as an LTS release.

In various products or places, we commonly interchange whether 22.04 or Jammy is used, however we have recently used the version number in some new places. For example, juju 3.x uses Ubuntu 'bases' of ubuntu@22.04, deprecated the older method of specifying 'series: jammy'. Ideally we'd have at a minimum consistency but realistically just display both in as many scenarios as possible.

While I work on Ubuntu every day and I mostly have the version to release name memorised, I struggle with this in other projects, for example OpenStack. I am sure the same happens for people using Ubuntu.

![Screenshot 2023-08-09 at 1 29 03 pm](https://github.com/canonical/lxd-ui/assets/290673/e8f97bd3-7e9f-4f1a-b3ad-78e32d0a82d2)

**Comment by edlerd** [comment]
Thank you for the detailed report, this is easy to fix, see above PR.
