### ISSUE TITLE
images list is empty

### ISSUE THREAD

**Issue by lateautumn233** [canonical/lxd-ui#437]
I am running lxd on Android and it works well, But I encountered some problems when creating instances using lxd ui.

Only after switching the architecture can it be displayed normally

https://qiuqiu233.top/软件/tmp/Video_1693398191573.mkv

**Comment by edlerd** [comment]
Thank you for reporting this! We only list the images that are supported by the LXD server which seems to work fine. But it seems the default filter is a bit too opinionated and needs to be adjusted. I'll look into this shortly.

**Comment by lateautumn233** [comment]
Thank you and good luck to you
