### ISSUE TITLE
Instance Terminal Error: Connection closed abnormally in LXD UI (Server 5.17)

### ISSUE THREAD

**Issue by JasonBrannon** [canonical/lxd-ui#450]
**Description:**
I'm experiencing an issue with the LXD UI on a bare metal installation where the Instance Terminal doesn't successfully load the web-based terminal. Instead, an error message is displayed.

**Error**
The connection was closed abnormally, e.g., without sending or receiving a Close control frame

**System Details:**
OS: Ubuntu 22.04.3 LTS x86_64
Host: NUC11PAHi5 M15533-306
Kernel: 5.15.0-83-generic
Shell: bash 5.1.16

**LXD Version:**
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.17-e5ead86  25505  latest/stable  canonical✓  -

**Additional VM Info:**
Network Interface: Bridge
Image Info: Ubuntu jammy cloud all ubuntu/22.04/cloud

**Logs:**
VM Logs: All appear clean

disk.mount.log
qemu.log
qemu.early.log
LXD Logs: No evident issues

dnsmasq.lxdbr0.log
lxd.log.1

**Note:** Continuous monitoring of **sudo snap logs lxd.daemon -f** showed no abnormalities.

Any help diagnosing and resolving this issue would be greatly appreciated!

![InstanceTerminalError](https://github.com/canonical/lxd-ui/assets/13629948/0104e8ba-75df-45c8-a9d8-86764f37e05e)

**Comment by edlerd** [comment]
Thank you for reporting this issue.

I am having trouble reproducing with the information given. It would help if you provide some more detail as in the questions below:
- Does the Console tab for the instance work, or has it the same error?
- Are you using a proxy between your browser and lxd-ui / lxd api?
- Any errors in the dev console on encountering the broken terminal connection?
(The console is opened with F12 in most browsers -- be sure to select the console tab.)
- Any hints on the network tab in the console?
(The same console is opened with F12 as above -- this time go to the network tab and select websockets / WS).

**Comment by JasonBrannon** [comment]
**Instance Terminal Issue with VMs and not Containers**

**Issue Details:**

- The Console tabs (both Graphic and Text) function properly for VMs.
- No proxy is set up between the browser and lxd-ui/lxd api.
- Issue seems specific to VMs as the Instance Terminal operates as expected for Containers of the same Ubuntu cloud version **Ubuntu jammy ubuntu/jammy/cloud**.

**Console Findings:**

Errors present in the dev console when accessing VM terminal.
Images attached highlighting the differences in network console results between VMs and Containers.

![Container-Network](https://github.com/canonical/lxd-ui/assets/13629948/40ad2f37-0f4d-4df4-aba3-39137992e20f)
![VM-Network](https://github.com/canonical/lxd-ui/assets/13629948/9ddf908d-1d64-4c28-8f69-f0966a92d272)


Images attached showing the differences in WebSocket results between VMs and Containers.

![Container-WS-Console](https://github.com/canonical/lxd-ui/assets/13629948/b9d316d7-72e7-4b64-a4e2-cbb2c0b91491)
![VM-WS-Console](https://github.com/canonical/lxd-ui/assets/13629948/a67127b2-ad6a-4636-be46-2e79513a2476)

**Comment by edlerd** [comment]
Thank you for providing the detailed description and screenshots.
I was now able to reproduce it and find and fix the underlying problem. You can expect the next LXD 5.18 to include the fix.

**Comment by JasonBrannon** [comment]
@edlerd Thanks! I appreciate the resolution, I can confirm on my production deployment of `5.18-ui-0.1` that Terminal to VMs capability has been restored.
