### ISSUE TITLE
Clearly distinguish LXD instances in page title

### ISSUE THREAD

**Issue by rptb1** [canonical/lxd-ui#464]
If you have multiple LXD UIs open in, e.g. Firefox tabs, then it's very hard to tell them apart.  The tabs are all named "LXD UI", and the pages are all visually the same with the name "Canonical LXD" at the top left.

![image](https://github.com/canonical/lxd-ui/assets/419807/b0f6ddd6-3658-4643-8157-0d4d031f0917)

Compare this with e.g. Syncthing, where each instance has a name, that name is the in name of the tab, and is clearly displayed at the top of the page.

![image](https://github.com/canonical/lxd-ui/assets/419807/72cd1111-2dc0-457c-a769-0bb978e28f97)

Please consider adding a something to the LXD UI, ideally settable from the Settings page.

It would be nice if the defaults for this setting at least included the hostname.

Thanks!

**Comment by edlerd** [comment]
Hello,

thank you for your request.

It makes a lot of sense to expose a cluster identifier in the title. I think we should add the currently viewed context to the title as well. Something like `myhost | project foo | instance bar | terminal`

Though, I am not so clear how to get the host identifier. The URL would give us just an IP in many cases, which might be less useful. Storing a customizable `user.hostname` value in the settings is a way, but we should also find a good solution for default clusters without that customization.

Kind regards,
David

**Comment by rptb1** [comment]
Many thanks for quickly implementing half of the request.

Would you like me to raise another issue for the other half?  That is, showing the hostname on the page itself?

**Comment by edlerd** [comment]
I doubt we need to show the name in the page as well. It will take precious space and attention from the "actual" page content.

Why is it necessary to show the name in the title and in the page? Especially in light of the title (including the name) being always visible in the important contexts, like when switching between tabs or on desktop.

If showing the name in the page as well is important to you, please reopen or open a new issue with a rationale as to why that should be done. Happy to continue the discussion here or in a new issue.
