### ISSUE TITLE
Bypass certificate authentication?

### ISSUE THREAD

**Issue by PBXForums** [canonical/lxd-ui#528]
Is there any way to bypass certificate authentication and just whitelist an IP for example?

I am using teleport (https://goteleport.com) to access all my services and just cannot seem to get this working?

Thanks
Daz

**Comment by edlerd** [comment]
You can setup a proxy presenting the client cert in front of LXD itself and have an allowed IP list in the proxy frontend.

You can find an example config for haproxy at https://github.com/canonical/lxd-ui/blob/main/haproxy-dev.cfg#L21

**Comment by PBXForums** [comment]
@edlerd Thank you very much, that worked perfectly.
