### ISSUE TITLE
Am I misunderstanding the install instructions does LXD-ui require Docker?

### ISSUE THREAD

**Issue by bmullan** [canonical/lxd-ui#531]
If I read the install instructions right _does **dotrun** (subsequently LXD-ui also) require Docker?_

Why not just build LXD-ui using LXD ?    Just seems odd!

Just curious why that approach was chosen.

**Comment by edlerd** [comment]
> If I read the install instructions right _does **dotrun** (subsequently LXD-ui also) require Docker?_

Dotrun is used as part of the development environment of LXD-UI. It is neither used for the production build nor shipped as part of the snap, when the LXD-UI is bundled with LXD.

> Why not just build LXD-ui using LXD ? Just seems odd!

A bit of background to make it easier to understand: Dotrun is a convenience tool for developers among the web team. We use it for websites and web projects. The goal is: one can check out a new repository and with the single command have the project up and running. I see, for LXD-UI this might seem odd, then again for internal tooling if something is in place and works, it is likely to be used as it is. We might revisit how dotrun operates and which technology it is based on in the future. Or we might change the dev environment for LXD-UI to be not dotrun based.

> Just curious why that approach was chosen.

Hope the above explanation helps, let me know if you have further questions.
