### ISSUE TITLE
Bug: Terminal is messy when redrawing

### ISSUE THREAD

**Issue by Igorgro** [canonical/lxd-ui#537]
When using commands in terminal that cause redrawing (for example `apt upgrade`, see last line on screenshot), then terminal becomes polluted with leftover characters.

![image](https://github.com/canonical/lxd-ui/assets/22894169/85f4358b-214c-4f6a-b496-25756294a4a5)

**Comment by edlerd** [comment]
Hi @Igorgro thank you for the report.

I am having trouble reproducing the behaviour. Did you resize the browser window while apt was running?

Thank you,
David

**Comment by Igorgro** [comment]
@edlerd , no I don't. I just connected to container (Debian 12) and run `apt upgrade`

**Comment by edlerd** [comment]
Thank you for the feedback! Unfortunately, I still can't reproduce it. I tested with a Debian 12 container and ran apt to install some packages.

- Does the screenshot from the terminal above contain the full terminal? So you had 10 lines height -- or was it bigger than what is visible there?
- Did you have other interactions with the UI at that time? Maybe closing a notification or similar during the terminal session?

**Comment by Igorgro** [comment]
1. This is a cropped screenshot, but there is nothing interesting on previous lines, just 30+ lines of `Get:xx http://deb.debian.org/...`
2. No, but I'm going to make a screen record next time I will do this

**Comment by edlerd** [comment]
Another idea: Which browser do you use, is it Firefox? I think I saw something similar to the root cause when testing there.

**Comment by Igorgro** [comment]
No, Google Chrome 119.0.6045.123

**Comment by Igorgro** [comment]
https://github.com/canonical/lxd-ui/assets/22894169/c345f1c3-1eac-4045-a3f4-b97603e5830c

**Comment by edlerd** [comment]
Thanks again for the video, I found one issue. It is fixed in the linked PR. It might be a tad too late to make it into LXD 5.20, but the next release will include the fix for sure.

**Comment by Igorgro** [comment]
I use the latest build from the main so I can test it as soon as it merged 😉
