### ISSUE TITLE
Can't select profiles, instance type or cluster member when creating new instance before an image has been selected

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd-ui#548]

**Comment by edlerd** [comment]
That is by design, the base image is the only mandatory information, hence all fields are locked until an image is selected.

**Comment by tomponline** [comment]
It feels quite awkward from a user perspective - I'd have expected to be able to select container/VM first and then select base image (filtered by type selected). Also the profiles and cluster member aren't related to instance type AFAIK so doesn't seem like a need to lock those before image selection, or is there?

**Comment by edlerd** [comment]
True, those are not dependant. I think we want to focus the user on the necessary choice of base image first, that is why most fields are locked initially.

For the vm/container selection -- it can be done in the image selection modal and the choice will be remembered in main form once an image is selected.
