### ISSUE TITLE
New instance being created disapears from instance list momentarily when it is being started

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd-ui#549]
When a new instance is being created it appears in the instance list and then it disappears momentarily when it is being started after creation.

**Comment by edlerd** [comment]
I can't reproduce it. Has this been tested with an older version of the UI, maybe?

**Comment by tomponline** [comment]
lxd 5.19-ui-0.4

**Comment by edlerd** [comment]
Right, I found it, will send a PR shortly.

**Comment by tomponline** [comment]
Thanks!
