### ISSUE TITLE
Select all N project instances

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd-ui#552]
I wondered why this part says "Select all N project instances" rather than "Select all N instances", why was the word project added here?

Thanks
![Screenshot 2023-11-23 at 13-18-31 10 21 203 5 LXD UI](https://github.com/canonical/lxd-ui/assets/280181/695a1b39-26a6-47e2-9daa-e8788d3e6738)

**Comment by edlerd** [comment]
We wanted to avoid implying this is about all instances on this server. The instance list is in context of a project, so we mention "project instances". This seems especially important, when many instances are available.

Do you think this should just say "select all n instances" without the project mentioned?

**Comment by tomponline** [comment]
Yeah you could say "select all n instances listed" perhaps to show its only selecting the ones being shown.

**Comment by edlerd** [comment]
> Yeah you could say "select all n instances listed" perhaps to show its only selecting the ones being shown.

When multiple pages are available, you might see only part of the instances that are about to be selected.

**Comment by piperdeck** [comment]
> When multiple pages are available, you might see only part of the instances that are about to be selected.

This was the primary factor in the wording of this prompt. There are several potential scopes of a "select all" action, and we wanted to be as unambiguous as possible. In this case, clicking the button will select all instances in this project, including instances not shown by the current pagination, but not including other instances on the server.

**Comment by piperdeck** [comment]
FWIW, I've done some user testing on this pagination and my users seemed to understand and be comfortable with what's going on

**Comment by tomponline** [comment]
To me instances are inherently linked to a project so "project instances" == "instances" , so the word "project" is effectively redundant. If it said "instances in project x" that would be clearer in my view.

**Comment by piperdeck** [comment]
I see what you mean. That works for me :+1:
