### ISSUE TITLE
Question regarding authentication

### ISSUE THREAD

**Issue by AidenWTF** [canonical/lxd-ui#566]
If i understood correctly, all of the authorisation is happening through selecting the right certificate ?
So only certificates i trusted in the server itself will be able to access the panel as long as i have the certificate added and selected in the Browser ?

**Comment by edlerd** [comment]
Yes that is partly correct. We also support login via OIDC today. You need to bring your own login provider and configure LXD for it.

We are planning to work on other life authentication methods in the near future (early 2024) to simplify the auth setup without certificates in the browser.
