### ISSUE TITLE
Add User Management

### ISSUE THREAD

**Issue by TorbenMartin** [canonical/lxd-ui#567]
Is it possible to Manage Users/Certificates and add different Roles/Groups/Permissions?

**Comment by edlerd** [comment]
You can use your own identity provider with OIDC. We also have plans to improve the setup for this early next year.

**Comment by TorbenMartin** [comment]
Thanks.

https://documentation.ubuntu.com/lxd/en/latest/authentication/

..."OpenID Connect authentication is currently under development. Starting with LXD 5.13, authentication through OpenID Connect is supported, but there is no user role handling in place so far. Any user that authenticates through the configured OIDC Identity Provider gets full access to LXD."...


and that is what i am missing. i want a normal usermanagement inside lxd-ui as internal menu for:

- add/remove/edit/enable/disable user accounts.
- allow management of VM1, VM2 and container 1, but not VM3-10
- allow read only on VM5-10

...something like that. better it would be with ldap integration

**Comment by TorbenMartin** [comment]
Thanks. 

I will take a look on "project per user" .... 
and hope next year will be a better year. :D 

i am a proud Ubuntu Poweruser and at Home i love many things with Enterprise Abilities. It just makes the life easier.

lxd-ui is some kind of "Feature" that can be great i guess with a little bit more "what a freak need"

**Comment by edlerd** [comment]
> With OIDC the user and account management is happening in a third party provider, which is possible to do today. You can also limit access by project per user with this solution as of today.

I have to revoke the last bit of this statement. As of today, users authenticated with OIDC always have full access. This will be changed shortly. So limiting access with OIDC will be possible in a future release.
