### ISSUE TITLE
Update OIDC cookie name

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd-ui#569]
When https://github.com/canonical/lxd/pull/12628 is merged. The name of the `oidc_access` cookie will change to `oidc_identity`. It should be a simple search and replace :) 

I can see that this is referenced in two places: https://github.com/search?q=repo%3Acanonical%2Flxd-ui%20oidc_access&type=code

**Comment by stgraber** [comment]
Probably want to support both names to avoid breaking current users.
