### ISSUE TITLE
UI fails to login when the user isn't allowed access to the `default` project

### ISSUE THREAD

**Issue by stgraber** [canonical/lxd-ui#575]
In an environment where the user isn't allowed access to the `default` project, the UI just fails and goes back to the login page.

That's despite the UI having successfully retrieved `/1.0/projects` and therefore knowing the list of available projects and being able to detect that the `default` project isn't one of those.

I suspect you probably want to just pick the first project in the list if `default` isn't part of it.

![image](https://github.com/canonical/lxd-ui/assets/2230599/5a540697-2282-40c0-bf47-bd18bdad512e)

**Comment by stgraber** [comment]
In my case, this is an OIDC + OpenFGA environment, but you should be able to reproduce the same by restricting a TLS certificate to a single project (restricted=true projects=[foo])

**Comment by edlerd** [comment]
Thank you for submitting the issue!

We rely solely on certificates to figure out if the user is restricted, and what the default project is in that case in the [auth provider ](https://github.com/canonical/lxd-ui/blob/main/src/context/auth.tsx#L43C14-L43C14).

Luckily, this should be easy to fix. I'll take a look at this shortly.

**Comment by stgraber** [comment]
Ah, that's an interesting approach fetching the restrictions on the certificate to figure out what projects can be accessed, though indeed since you also fetch the full list to populate the drop-down, might as well use that data instead as it will work in all cases :)

**Comment by edlerd** [comment]
> Ah, that's an interesting approach fetching the restrictions on the certificate to figure out what projects can be accessed, though indeed since you also fetch the full list to populate the drop-down, might as well use that data instead as it will work in all cases :)

Turns out, the OIDC based login is always giving full access at the moment. We have no option to figure out a user is restricted than looking at the certificate that is in use. Because the `GET /1.0` contains no information of which permissions a user has. Though this will change shortly and I think we should keep this issue open until the backend support is ready for this to be fixed.

**Comment by stgraber** [comment]
I'm confused, you already query /1.0/projects, the list of projects returned in that case will be limited to those the user can access.

So if you are dealing with a restricted certificate, you'll get a subset of projects returned through GET /1.0/projects and the same is true under OIDC+OpenFGA (REBAC).

What you won't know is whether you have full server admin capabilities or not, I suppose that could be added to the metadata in /1.0, but until such time you can take the shortcut of checking if default is in the project list, if it is, there's a very very good chance that you are an admin.

**Comment by edlerd** [comment]
Right, I can change the default project selection to rely on the available project list. Will open a PR for it now with other small fixes related to restricted access users.

**Comment by stgraber** [comment]
Thanks!
