### ISSUE TITLE
Add support podman/docker

### ISSUE THREAD

**Issue by TorbenMartin** [canonical/lxd-ui#588]
It would be nice to have podman/docker support similar like podman management in cockpit-podman.
is it possible to integrate cockpit-podman or another management solution direct in the lxd ui?

then have everything important together: lxc, vm, docker/podman

**Comment by TorbenMartin** [comment]
Its just an "smart" idea for bring everything together.
I dont want different Solutions.

I want only 1 Place for manage all. That redjuce complexity.

OpenShift can manage VMs and podman container
LXD/lxc can manage VMs and lxc
RHV can manage VMs
cockpit can manage VMs and docker/podman
portainer can manage docker
rancher can manage docker

there are a lot Solutions.. but nothing supports all 3.

i would recommend something like cockpit-podman ...

but i want be able to manage that from lxd UI.
i think with more solutions in one... more people also would use it.

and this can be a "pro" also for enterprise usage.

**Comment by edlerd** [comment]
It is not our focus in LXD-UI to integrate with the mentioned tools. We might revisit this at a later time.
