### ISSUE TITLE
LXD web UI 

### ISSUE THREAD

**Issue by nas-maker** [canonical/lxd-ui#612]
I have a problem in lxD web ui, when I refresh the page the terminal stop, when I install a package and refresh the page, the package stops installing

**Comment by edlerd** [comment]
Yes, that is expected. When the terminal page is reloaded (or being closed), the underlying web socket disconnects and running processes stop.

You can keep the process running in the background with tools like tmux or screen.

Closing the issue as it is not an issue with LXD UI itself.
