### ISSUE TITLE
[FR] Allow deleting images by selection box/checkbox, similar to how deleting instances is today

### ISSUE THREAD

**Issue by desrod** [canonical/lxd-ui#618]
While deploying and wiping LXD containers, VMs and images to test the caching of an upstream MiTM SSL proxy, it became clear that deleting the images from the UI is a lot more work than it could be, for large numbers of images. 

I'm proposing that the same methodology that is used in the instance list be used in the image list, so I can "select all" images and delete them in one shot, vs. clicking the little trash can to the right of each image directly. 

Yes, I can also do this via the CLI using `lxc image list -f json | jq -r '.[].fingerprint' | xargs rm`, but that's still clunky on its own. 

Ideally, something that allows the reuse of the same UX/components used elsewhere in the LXD UI would be ideal. 

Additionally, the ability to search for images/instances by a partial naming convention, and then "select all" of those matching for deletion, would be useful.

**Comment by edlerd** [comment]
Thank you for the request.

> I'm proposing that the same methodology that is used in the instance list be used in the image list, so I can "select all" images and delete them in one shot, vs. clicking the little trash can to the right of each image directly.
> [...] 
> Ideally, something that allows the reuse of the same UX/components used elsewhere in the LXD UI would be ideal.

Yes, this sounds reasonable and like an easy addition, we will look into it.

> Additionally, the ability to search for images/instances by a partial naming convention, and then "select all" of those matching for deletion, would be useful.

You can enter text in the image lists "search and filter" component on top of the page. On "Enter" press, the query will be partially matched against instance names and their base images. We don't advertise the feature well in the UI yet, though I think this satisfies your additional request.
