### ISSUE TITLE
LXD zone transfer configuration breaks after reboot. 

### ISSUE THREAD

**Issue by ilyaredis** [canonical/lxd-ui#670]
Hi all,

I am consistently running into an issue after configuring the Zone transfer feature with LXD
For the guidelines I use this page and the demo here: https://documentation.ubuntu.com/lxd/en/stable-5.0/howto/network_zones/
I also use the configuration with port 8853 like so:
`lxc config set core.dns.address 10.157.229.1:8853`

My DNS server (I also use NSD) is also deployed locally as a VM on the host machine. And once configured it all works as described.
However, The issue is that once I reboot the host machine, the NSD server fails to connect on the same port. the issue is unrecoverable and requires setup anew.

here is the journalctl -f log fragment from the NSD server:
`Feb 23 01:54:05 ns1 nsd[397]: redistest.com: Could not tcp connect to 10.157.229.1@8853: Connection refused
Feb 23 01:54:05 ns1 nsd[397]: 229.157.10.in-addr.arpa: Could not tcp connect to 10.157.229.1@8853: Connection refused
`
Please advise if it is a known issue and if workaround is available.

Thanks!

**Comment by ilyaredis** [comment]
Just noticed that I opened this issue for LXD-UI instead of LXD. Should I close and reopen in LXD?

**Comment by edlerd** [comment]
As this seems not like a UI issue:

Please ask for help in the [LXD discourse forum](https://discourse.ubuntu.com/c/lxd/126), or if you think this is a bug, please file an issue on the [LXD repository](https://github.com/canonical/lxd).
