### ISSUE TITLE
Support for new Dell PowerFlex storage driver

### ISSUE THREAD

**Issue by roosterfish** [canonical/lxd-ui#677]
Hello,

recently we have added support for the new Dell PowerFlex storage driver in LXD (https://github.com/canonical/lxd/pull/12304). The UI should also grow support for managing PowerFlex pools and volumes.

Whilst displaying the pool already works like expected, there seems to be an issue when trying to create custom storage volumes: 

![Screenshot from 2024-02-26 15-25-19](https://github.com/canonical/lxd-ui/assets/6641364/80f5fe48-f5e9-4ed9-bd29-b59758a5b791)

It looks that also the pool creation requires some additional changes to accommodate the new driver.

The specification for the driver can be found in https://discourse.ubuntu.com/t/dell-powerflex-storage-driver/40611/6.
The end user documentation is in https://documentation.ubuntu.com/lxd/en/latest/reference/storage_powerflex/.

**Comment by edlerd** [comment]
Thank you for the request.
I [opened a PR](https://github.com/canonical/lxd-ui/pull/679) to add the driver and relevant fields to the UI. Also note, there is a [very recent PR adding yaml support for storage drivers](https://github.com/canonical/lxd-ui/pull/676), enabling configuration of all powerflex options.
