### ISSUE TITLE
On the instances -> (vm) -> graphic console page, if browser aspect ratio is too wide, the bottom of the console is cut off

### ISSUE THREAD

**Issue by cmspam** [canonical/lxd-ui#700]
I think it is necessary to implement resizing of the console interface differently for VMs and LXC containers, to allow scrolling down.  As in the attached screenshot, with the web browser window beyond a certain aspect ratio, the bottom of the console is cut off. (This is not an issue with containers, only with VMs.)

One either needs to make the console full screen, decrease the size of text in the browser, or resize the aspect ratio of the browser window in order to see the bottom of the console.

I think this could be resolved in one of two ways:
* Allow the console to be oversized beyond the size of the browser window, and let the user scroll down.
* Force the console to be a certain aspect ratio despite browser window aspect ratio if it is a VM.

I hope I can have your consideration in fixing this.

See screenshot:

<img width="1111" alt="image" src="https://github.com/canonical/lxd-ui/assets/2881049/57b9d4d1-092b-4a13-8fc8-a5ae48f18cf5">

**Comment by edlerd** [comment]
Thank you for your report. I am failing to reproduce it just yet.

Can you please share which OS and Browser you are using, as well as the version of LXD?

I tested with the latest stable version `lxd 5.20-f3dd836`. It shows a scrollbar for me in the screen you mention. See the screenshot below.

Maybe you are on macOS without visible scrollbars? I have seen it as a setting before. With it, you only see the scrollbars, once the mouse pointer is close to them.

Another question: Have you tried running any real desktop, like Ubuntu mantic desktop or alpine desktop? Those should be fully responsive, and the Graphic console will adjust to the browser screen size.  Just in the early boot times (like in your screenshot) we can't tell the guest OS a screen size, hence the only solution is to display a scrollbar if the browser window is too small. Then again, this scrollbar seems to not show in your case, and that is still a bit of a mystery to me.

![image](https://github.com/canonical/lxd-ui/assets/1155472/0a41fe74-f8fd-4985-88e0-6b40ae1176be)

**Comment by cmspam** [comment]
Yes, I am actually on MacOS without visible scrollbars in this case. The issue is the same in all browser I have tried, Safari, Chrome, Brave...
When enabling visual scrollbars, I see the scrolling functionality you've shown.

Normally, I would scroll with my track pad, using two-finger gestures, or even use the down arrow key on the keyboard. Without visual scrollbars (which is the default in macOS), there is no way to scroll this part of the interface down... the gestures don't work at all.

I am sure that the reason is likely because the VM would be using the scrolling gestures, so they are disabled from the interface. Could it be modified so that, for example, if the mouse cursor is over a part of the screen which is not part of the VM console, the two finger scrolling could be enabled?

**Comment by edlerd** [comment]
Thanks for confirming that this is an issue with the hidden scrollbars on MacOS. I think the VM doesn't propagate scroll activity to the parent container when hovering it's container. We might be able to change this, because it seems like the expected behaviour from any user. And at least theoretically I can't see a negative side effect, just need to check feasibility early next week.

**Comment by cmspam** [comment]
@edlerd Thank you for your fix. I had a chance to test it.

There is one slight adjustment I hope can be made.
In order to do two finger scrolling on a mac laptop, I need to be able to get the cursor below the display of the VM. It doesn't work when the mouse is on the white borders to the left and right of the VM. 

In other words, unless the height of the console is already small enough that I can see all of it, there is no place I can put my cursor to enable the two finger scrolling to scroll it down. On a mac laptop with hidden scrollbars, this issue still persists, unfortunately.

There are white borders on the left and right of the console, which I hope could be enabled as an area to place my cursor and have two-finger scrolling be enabled, if possible.

If not, it's not a huge inconvenience, but it would be very helpful.

For reference, see the screenshot. With the window this size, there is no way at all to scroll down without resizing the window.

![screenshot1](https://github.com/canonical/lxd-ui/assets/2881049/bb23e0b3-3dbd-4b08-9e11-24b972fcc607)

**Comment by edlerd** [comment]
Thank you fore reporting back. There was an issue in the previous patch. Luckily it was easy to reproduce and fix it right away.

**Comment by cmspam** [comment]
You're very fast! Thanks a lot.
