### ISSUE TITLE
when I use default profile  in lxd 5.21

### ISSUE THREAD

**Issue by knonots** [canonical/lxd-ui#734]
Instance start failed
Instance win11: Failed to run: forklimits limit=memlock:unlimited:unlimited fd=3 fd=4 -- /snap/lxd/28155/bin/qemu-system-x86_64 -S -name win11 -uuid 4e4dad15-a3b1-4f55-bb87-12c3df74864b -daemonize -cpu host,hv_passthrough -nographic -serial chardev:console -nodefaults -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=allow,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/win11/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/win11/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/win11/qemu.pid -D /var/snap/lxd/common/lxd/logs/win11/qemu.log -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd -device intel-hda -device hda-duplex: : exit status 1

**Comment by edlerd** [comment]
Thank you for reaching out.

Is this a UI problem, or do you use the command line? In the later case, please report to [LXD directly](https://github.com/canonical/lxd-ui/issues/new) (this is the UI repository). Probably the fastest responses would be through the [community forum](https://discourse.ubuntu.com/c/lxd/126).
