### ISSUE TITLE
Images does not replicates across the cluster

### ISSUE THREAD

**Issue by norbertoisaac** [canonical/lxd-ui#767]
Hi there
Images does not replicating across all cluester nodes, it is correct?

cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

lxd --version
5.21.1 LTS

lxc config set cluster.images_minimal_replica=3

lxc config get cluster.images_minimal_replica     <---- this command returns empty

lxc cluster list
+-------------+-----------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
|    NAME     |             URL             |      ROLES      | ARCHITECTURE | FAILURE DOMAIN | DESCRIPTION | STATE  |      MESSAGE      |
+-------------+-----------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| fdo-kvmc1h1 | https://[100::2004:68]:8443 | database        | x86_64       | default        |             | ONLINE | Fully operational |
+-------------+-----------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| fdo-kvmc1h4 | https://[100::2004:71]:8443 | database-leader | x86_64       | default        |             | ONLINE | Fully operational |
|             |                             | database        |              |                |             |        |                   |
+-------------+-----------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| fdo-kvmc1h5 | https://[100::2004:72]:8443 | database        | x86_64       | default        |             | ONLINE | Fully operational |
+-------------+-----------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+

lxc image list
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                     DESCRIPTION                     | ARCHITECTURE |      TYPE       |   SIZE    |          UPLOAD DATE          |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 0cedc56037a0 | no     | Fedora 40 amd64 (20240513_0004)                     | x86_64       | VIRTUAL-MACHINE | 529.45MiB | May 13, 2024 at 7:06pm (UTC)  |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 8eb4fdeefd99 | no     | Arch Linux current amd64 (20240502_0003)            | x86_64       | CONTAINER       | 209.38MiB | May 10, 2024 at 11:33pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 34b811dd4d43 | no     | AlmaLinux 8 amd64 (20240510_0010)                   | x86_64       | VIRTUAL-MACHINE | 769.52MiB | May 10, 2024 at 11:32pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 52f50bba1ed4 | no     | Arch Linux current amd64 (20240502_0003)            | x86_64       | VIRTUAL-MACHINE | 554.59MiB | May 10, 2024 at 11:34pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 58c0c6839eef | no     | Alpine 3.19 amd64 (20240510_0017)                   | x86_64       | CONTAINER       | 20.96MiB  | May 11, 2024 at 12:59am (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 63e801c05439 | no     | ubuntu 24.04 LTS amd64 (release) (20240423)         | x86_64       | VIRTUAL-MACHINE | 453.00MiB | May 10, 2024 at 11:40pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 64c889060085 | no     | ubuntu 24.04 LTS amd64 (minimal release) (20240423) | x86_64       | CONTAINER       | 114.69MiB | May 10, 2024 at 11:37pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | 78f29baf4de7 | no     | Debian bookworm amd64 (20240510_0002)               | x86_64       | CONTAINER       | 95.82MiB  | May 10, 2024 at 11:19pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | ada8c13435f1 | no     | CentOS 8-Stream amd64 (20240510_0019)               | x86_64       | CONTAINER       | 150.79MiB | May 10, 2024 at 11:28pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | c2d480b0ac0b | no     | openSUSE 15.5 amd64 (20240513_0018)                 | x86_64       | VIRTUAL-MACHINE | 827.20MiB | May 13, 2024 at 5:40pm (UTC)  |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | c3edde4e2126 | no     | AlmaLinux 8 amd64 (20240510_0010)                   | x86_64       | CONTAINER       | 148.38MiB | May 10, 2024 at 11:30pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | c56a43b9cf64 | no     | CentOS 8-Stream amd64 (20240510_0019)               | x86_64       | VIRTUAL-MACHINE | 858.88MiB | May 10, 2024 at 11:29pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | c83743c7e46a | no     | Debian bookworm amd64 (20240510_0002)               | x86_64       | VIRTUAL-MACHINE | 350.89MiB | May 10, 2024 at 11:25pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | ca5857fe2df4 | no     | Oracle 9 amd64 (20240513_0011)                      | x86_64       | CONTAINER       | 138.20MiB | May 13, 2024 at 7:16pm (UTC)  |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | dddcca675559 | no     | ubuntu 24.04 LTS amd64 (minimal release) (20240423) | x86_64       | VIRTUAL-MACHINE | 227.19MiB | May 10, 2024 at 11:37pm (UTC) |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+
|       | f99b84e233d7 | no     | Fedora 40 amd64 (20240513_0004)                     | x86_64       | CONTAINER       | 113.42MiB | May 13, 2024 at 7:07pm (UTC)  |
+-------+--------------+--------+-----------------------------------------------------+--------------+-----------------+-----------+-------------------------------+

On fdo-kvmc1h1
root@fdo-kvmc1h1:~# ls -l /storage/btrfsVol1/subVolLxd/images/
total 0
drwx--x--x 1 root root 60 May 13 18:07 34b811dd4d43e087bc83c5e65e5eeeda0a7aad89f4cc2d7d79cc5a51c7c5ee9e
drwx--x--x 1 root root 56 May 10 23:54 64c889060085048b9a39cd3b82864497bb5de6f510b896d2648ed43e751264e4
drwx--x--x 1 root root 60 May 13 18:05 c2d480b0ac0b2a99b6b97f2ff80873d8ea48ef7edcd43565e2f4918bca96bd50
drwx--x--x 1 root root 56 May 13 19:16 ca5857fe2df4c66036f7411c7c62c2203d00b91e6d9de99a174838d2fbe2fca8

On fdo-kvmc1h4
root@fdo-kvmc1h1:~# ls -l /storage/btrfsVol1/subVolLxd/images/
total 0
drwx--x--x 1 root root 60 May 13 19:06 0cedc56037a068f4cf71de908530c05f5b2fa1a9cfa7b1559a86c374bca8ee61
drwx--x--x 1 root root 60 May 11 00:23 63e801c054391f66daa35b8d0205d92b7e405092546f9df2e4be2adb2e08a71d
drwx--x--x 1 root root 56 May 13 19:07 f99b84e233d7d74dffbf60e5c4919a473242ec104acc2d36d646e0c4126e3d46

On fdo-kvmc1h4
root@fdo-kvmc1h5:~# ls -l /storage/btrfsVol1/subVolLxd/images/
total 0
drwx--x--x 1 root root 56 May 11 00:59 58c0c6839eef1406240aa22047f35b5dce4bde8649e324cf2e8b44aad7314842

lxc list
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
|       NAME        |  STATE  |         IPV4          |                      IPV6                       |      TYPE       | SNAPSHOTS |  LOCATION   |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| Minimal           | RUNNING | 10.14.217.217 (eth0)  | fd42:f300:9e4c:6b87:216:3eff:feb4:a966 (eth0)   | CONTAINER       | 0         | fdo-kvmc1h5 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| accepted-gull     | RUNNING | 10.14.217.102 (eth0)  | fd42:f300:9e4c:6b87:75c6:4364:f3cb:3f1d (eth0)  | VIRTUAL-MACHINE | 0         | fdo-kvmc1h1 |
|                   |         |                       | fd42:f300:9e4c:6b87:216:3eff:fe6b:e9d (eth0)    |                 |           |             |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| apparent-arachnid | RUNNING | 10.14.217.153 (eth0)  | fd42:f300:9e4c:6b87:216:3eff:fe13:fc7 (eth0)    | VIRTUAL-MACHINE | 0         | fdo-kvmc1h1 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| mature-kit        | RUNNING | 10.14.217.247 (eth0)  | fd42:f300:9e4c:6b87:216:3eff:fe22:9a5c (eth0)   | CONTAINER       | 0         | fdo-kvmc1h4 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| on-escargot       | RUNNING | 10.14.217.77 (enp5s0) | fd42:f300:9e4c:6b87:216:3eff:fe7b:17e2 (enp5s0) | VIRTUAL-MACHINE | 0         | fdo-kvmc1h5 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| trusting-python   | RUNNING | 10.14.217.73 (eth0)   | fd42:f300:9e4c:6b87:216:3eff:fea4:51be (eth0)   | CONTAINER       | 0         | fdo-kvmc1h1 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| vast-cat          | RUNNING | 10.14.217.39 (eth0)   | fd42:f300:9e4c:6b87:216:3eff:fe90:cccc (eth0)   | CONTAINER       | 0         | fdo-kvmc1h5 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+
| warm-flounder     | RUNNING | 10.14.217.81 (enp5s0) | fd42:f300:9e4c:6b87:216:3eff:fe5d:6934 (enp5s0) | VIRTUAL-MACHINE | 0         | fdo-kvmc1h4 |
+-------------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+-------------+

**Comment by edlerd** [comment]
Thank you for reaching out.

Is this a UI problem, or do you use the command line? In the later case, please report to [LXD directly](https://github.com/canonical/lxd-ui/issues/new), as this is the LXD-UI repository. Probably the fastest responses would be through the [community forum](https://discourse.ubuntu.com/c/lxd/126).

**Comment by norbertoisaac** [comment]
Hi @edlerd 
My apologies, there was a misunderstand
