### ISSUE TITLE
Hide volume snapshot in "Choose custom volume" model

### ISSUE THREAD

**Issue by lijunle** [canonical/lxd-ui#777]
When choose to attach a disk to a container / VM, it opens the "Choose custom volume" model.

![Screenshot 2024-05-16 at 01 24 53](https://github.com/osamuaoki/incus-ui-canonical/assets/1296500/192f17c4-df78-442c-85a3-091498464019)

The model shows the custom volume with its snapshots. I could expect the snapshot should not be shown here. At least, we should hide them by default and provide a checkbox to show snapshots.

![Screenshot 2024-05-16 at 01 25 28](https://github.com/osamuaoki/incus-ui-canonical/assets/1296500/26769a11-2233-483d-99af-27e92368ca33)

Related code here: 

https://github.com/canonical/lxd-ui/blob/487ba59852dfec8c15601102df4ac8e41d7c04e9/src/pages/storage/CustomVolumeSelectModal.tsx#L29-L38

**Comment by edlerd** [comment]
Thank you for reaching out and reporting this issue. Indeed, this is a bug and can be fixed shortly.
