### ISSUE TITLE
keycloack oidc authentication logout error

### ISSUE THREAD

**Issue by cristianomeloni** [canonical/lxd-ui#796]
configuration with keycloack and ldap work well, but on logout no way to remove authentication.
click on login ask for password only 1st time, the login direcly.

**Comment by edlerd** [comment]
I think this is as intended with SSO. You log in to your 3rd party login provider once. When using that login provider in LXD-UI, LXD will redirect to the 3rd party. If you're already signed in there, you will immediately be redirected back to LXD-UI as authenticated.

So in your case you need to log out of the 3rd party provider, how to do that is outside LXD.

This is like with "sign in with github" on other pages. When I do that and sign out of the other page, I am still signed in to github.

Please reopen if you still think this is an issue.
