### ISSUE TITLE
I cannot create an image from a snapshot

### ISSUE THREAD

**Issue by tam1192** [canonical/lxd-ui#824]
I cannot create an image from a snapshot.
Specifically, this occurs when they are separated in a project.

```
Image creation from snapshot "first" failed.
Failed to fetch instance "test/first" in project "default": Instance not found
```

## reproduction method
1. Create a new project
2. Set up your project as follows
> Features: Customised
>
> Allow the following features:
>   - [ ] Images
>   - [x] Profiles
>   - [ ] Networks
>   - [ ] Network zones
>   - [x] Strorage buckets
>   - [x] Storage volumes    
3. Set up an instance as appropriate and take snapshots
4. When I try to create an image from snapshots, I get the following error
```
Image creation from snapshot "first" failed.
Failed to fetch instance "test/first" in project "default": Instance not found
```

## Assumed behavior
Same as the command line version.
The snapshot itself is recorded in the defalt project.

## Operating environment, etc.
```
uname -s -r
Linux 6.8.0-39-generic
```
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```
```
lxd --version
5.21.2 LTS
```
```
zfs --version
zfs-2.2.2-0ubuntu9
zfs-kmod-2.2.2-0ubuntu9
```

Please let me know if you need anything else.

**Comment by mas-who** [comment]
@tam1192 thank you for reporting this with detailed info! I was able to reproduce this on the latest branch. Will investigate and provide feedback soon.

**Comment by mas-who** [comment]
@tam1192 the [fix](https://github.com/canonical/lxd-ui/pull/825) for this issue just got merged. The `latest/edge` lxd snap channel should have the fix already, and the patch will be back-ported to earlier lxd versions for the next release.
