### ISSUE TITLE
certificate process works in firefox not in chrome

### ISSUE THREAD

**Issue by rbushglrc** [canonical/lxd-ui#880]
certificate process works as described in firefox not in chrome

**Comment by edlerd** [comment]
Thank you for the report. Which error are you facing with Chrome?

**Comment by rbushglrc** [comment]
Even after restart of chrome it was caching credentials i had to manually go clear all data for the site and repeat the procedure to add the certificate so the page would load.

--------------------- this message was forwarded by -------------------------------------
Ray Bush, Network and Systems Engineer,
Great Lakes Recovery Centers, Inc. - Administration Office
97 S. Fourth Street
Ishpeming, MI 49849
Phone: 906-228-9699 ext. 2603
Mobile: 906-485-1466
Fax: 906-228-0505
________________________________

**Comment by edlerd** [comment]
From what I understand, reading your last message, the issue seems resolved. Closing it for now.
