### ISSUE TITLE
Inquiry on Setting Up Caddy Reverse Proxy for LXD UI

### ISSUE THREAD

**Issue by cutiechi** [canonical/lxd-ui#950]
Hello,

I am looking for guidance on how to set up a reverse proxy using Caddy for the LXD UI. I would appreciate any steps or examples you could provide to help me configure this properly.

Here are a few specifics I’m interested in:

Basic configuration for Caddy to reverse proxy the LXD UI.
Any security considerations I should be aware of.
How to handle HTTPS with Caddy for the LXD UI.
Thank you for your assistance!

**Comment by edlerd** [comment]
Thank you for your request,

you can setup a proxy with lxd-ui, but you have to be careful with authentication:

1. If you use a client certificate for authenticating, the proxy must be setup on tcp level. This is mandatory for the mutual tls connection. This connection must be between your browser and lxd itself. If a proxy in between messes with https this will not work. With a proxy in tcp mode this should work fine.

2. Another option is to use a third party login provider with OIDC. This way you will login to a third party login provider and lxd can be run behind a proxy in http mode without problem. You can find guidance for a setup in the official documentation.

Hope this answers your question.

**Comment by edlerd** [comment]
Closing as this is not a feature for the ui, please consult the [public forum](https://discourse.ubuntu.com/c/lxd/126) for questions on the setup.
