### ISSUE TITLE
Guidance on Utilizing LXD Capabilities with Custom Management Portal

### ISSUE THREAD

**Issue by irtaza9** [canonical/lxd-ui#987]
I have successfully set up my infrastructure and now plan to create VMs and containers for various use cases. I also have a custom management portal that I use for managing the infrastructure. Since I have LXD configured on multiple hosts, I would like your guidance on effectively leveraging its capabilities, particularly through its REST API.

### Any tips on designing a scalable solution that can accommodate additional hosts or increased workload over time?

**Comment by edlerd** [comment]
Hello and thank you for the request.

Allow me a disclaimer:
This is the LXD-UI repo. It is for bugs and feature requests. Please post setup requests in the [public LXD forum](https://discourse.ubuntu.com/c/lxd/126).

To give you a very short answer to your questions before closing:
You probably want to look into [LXD clustering](https://documentation.ubuntu.com/lxd/en/stable-5.21/clustering/) and build clusters of up to 50 hosts. In LXD terminology, one host of a cluster is called a member. For infrastructure with more than 50 members, you best orchestrate multiple clusters with ~50 members each. I'd advise using one cluster per rack. But then again, to get more detailed answers, please consult the community forums or get [commercial support from canonical](https://canonical.com/lxd/install).
